In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn import linear_model
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.neighbors import KNeighborsClassifier


import pickle


In [2]:
data = pd.read_csv('iris.csv')
data.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [3]:
X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [5]:
classifierKNN = KNeighborsClassifier(n_neighbors=5)

In [6]:
classifierKNN.fit(X_train, y_train)

KNeighborsClassifier()

In [7]:
y_test_pred_KNN = classifierKNN.predict(X_test)

In [8]:
# prompt user input for a new sample
new_sample = []
for i in range(len(X_train[0])):
    feature = input(f'Enter the value of feature {i+1}: ')
    new_sample.append(float(feature))

# make a prediction on the new sample
y_pred = classifierKNN.predict(np.array(new_sample).reshape(1,-1))

# print the predicted label
print('Predicted label:', y_pred[0])

Enter the value of feature 1: 5.5
Enter the value of feature 2: 3.6
Enter the value of feature 3: 1.4
Enter the value of feature 4: .2
Predicted label: Setosa


In [9]:
accuracyKNN = accuracy_score(y_test, y_test_pred_KNN)
print(" Accuracy:", accuracyKNN*100, "%")

 Accuracy: 100.0 %


In [11]:
print(classification_report(y_test, y_test_pred_KNN))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        10
  Versicolor       1.00      1.00      1.00         9
   Virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [12]:
cm_DT = confusion_matrix(y_test, y_test_pred_KNN)
print(cm_DT)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


The model only requires the code 


classifierKNN.fit(X_train, y_train)

y_test_pred_KNN = classifierKNN.predict(X_test)


we don't need the user prompt since we will do that on our html and app.py since we are using flask




In [10]:

# save the trained model to a binary file named 'knn_model.pkl'
with open('knn_model.pkl', 'wb') as file:
    pickle.dump(classifierKNN, file)